[package]
name = "messages"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls"] }
